name: "ci runner for web app"
on: 
  push:
    branches:
      - master
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
    - name:  checkout to root directory
      uses: actions/checkout@v6

    - name: list the directory
      run: ls

